/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SistemaTiendaVideoJuegos.View;

/**
 *
 * @author Ramon Cheno Ocaño
 */
public class ProductosInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductosInfoPanel
     */
    public ProductosInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        clientesBtn = new javax.swing.JButton();
        productosBtn = new javax.swing.JButton();
        inicioPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosTable = new javax.swing.JTable();
        transformTxt = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        updateProductBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        insertProductBtn1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(0, 0, 204));
        menuPanel.setForeground(new java.awt.Color(0, 0, 0));
        menuPanel.setMinimumSize(new java.awt.Dimension(120, 600));
        menuPanel.setPreferredSize(new java.awt.Dimension(120, 600));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientesBtn.setBackground(new java.awt.Color(0, 0, 204));
        clientesBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clientesBtn.setText("Clientes");
        clientesBtn.setBorder(null);
        clientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesBtnActionPerformed(evt);
            }
        });
        menuPanel.add(clientesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        productosBtn.setBackground(new java.awt.Color(0, 0, 204));
        productosBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productosBtn.setText("Productos");
        productosBtn.setBorder(null);
        productosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosBtnActionPerformed(evt);
            }
        });
        menuPanel.add(productosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, -1));

        add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        inicioPanel.setBackground(new java.awt.Color(255, 255, 255));
        inicioPanel.setMinimumSize(new java.awt.Dimension(680, 600));
        inicioPanel.setPreferredSize(new java.awt.Dimension(680, 600));
        inicioPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tabla de productos");
        inicioPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 255));

        productosTable.setBackground(new java.awt.Color(0, 153, 255));
        productosTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productosTable.setForeground(new java.awt.Color(0, 0, 0));
        productosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(productosTable);

        inicioPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 620, 410));

        transformTxt.setBackground(new java.awt.Color(0, 51, 255));
        transformTxt.setForeground(new java.awt.Color(255, 255, 255));
        transformTxt.setText("ETL");
        inicioPanel.add(transformTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 51, 255));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Atras");
        inicioPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        updateProductBtn.setBackground(new java.awt.Color(0, 51, 255));
        updateProductBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateProductBtn.setText("Actualizar Producto");
        inicioPanel.add(updateProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Eliminar");
        inicioPanel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, -1));

        insertProductBtn1.setBackground(new java.awt.Color(0, 51, 255));
        insertProductBtn1.setForeground(new java.awt.Color(255, 255, 255));
        insertProductBtn1.setText("Ingresar Producto Nuevo");
        inicioPanel.add(insertProductBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        add(inicioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void clientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesBtnActionPerformed

    private void productosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productosBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clientesBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel inicioPanel;
    private javax.swing.JButton insertProductBtn1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton productosBtn;
    private javax.swing.JTable productosTable;
    private javax.swing.JButton transformTxt;
    private javax.swing.JButton updateProductBtn;
    // End of variables declaration//GEN-END:variables
}
